# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: niffler_currency.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'niffler_currency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16niffler_currency.proto\x12\x14guru.qa.grpc.niffler\x1a\x1bgoogle/protobuf/empty.proto\"I\n\x10\x43urrencyResponse\x12\x35\n\rallCurrencies\x18\x01 \x03(\x0b\x32\x1e.guru.qa.grpc.niffler.Currency\"\x80\x01\n\x08\x43urrency\x12;\n\x08\x63urrency\x18\x01 \x01(\x0e\x32$.guru.qa.grpc.niffler.CurrencyValuesH\x00\x88\x01\x01\x12\x19\n\x0c\x63urrencyRate\x18\x02 \x01(\x01H\x01\x88\x01\x01\x42\x0b\n\t_currencyB\x0f\n\r_currencyRate\"\xde\x01\n\x10\x43\x61lculateRequest\x12@\n\rspendCurrency\x18\x01 \x01(\x0e\x32$.guru.qa.grpc.niffler.CurrencyValuesH\x00\x88\x01\x01\x12\x42\n\x0f\x64\x65siredCurrency\x18\x02 \x01(\x0e\x32$.guru.qa.grpc.niffler.CurrencyValuesH\x01\x88\x01\x01\x12\x13\n\x06\x61mount\x18\x03 \x01(\x01H\x02\x88\x01\x01\x42\x10\n\x0e_spendCurrencyB\x12\n\x10_desiredCurrencyB\t\n\x07_amount\"G\n\x11\x43\x61lculateResponse\x12\x1d\n\x10\x63\x61lculatedAmount\x18\x01 \x01(\x01H\x00\x88\x01\x01\x42\x13\n\x11_calculatedAmount*E\n\x0e\x43urrencyValues\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03RUB\x10\x01\x12\x07\n\x03USD\x10\x02\x12\x07\n\x03\x45UR\x10\x03\x12\x07\n\x03KZT\x10\x04\x32\xce\x01\n\x16NifflerCurrencyService\x12R\n\x10GetAllCurrencies\x12\x16.google.protobuf.Empty\x1a&.guru.qa.grpc.niffler.CurrencyResponse\x12`\n\rCalculateRate\x12&.guru.qa.grpc.niffler.CalculateRequest\x1a\'.guru.qa.grpc.niffler.CalculateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'niffler_currency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CURRENCYVALUES']._serialized_start=581
  _globals['_CURRENCYVALUES']._serialized_end=650
  _globals['_CURRENCYRESPONSE']._serialized_start=77
  _globals['_CURRENCYRESPONSE']._serialized_end=150
  _globals['_CURRENCY']._serialized_start=153
  _globals['_CURRENCY']._serialized_end=281
  _globals['_CALCULATEREQUEST']._serialized_start=284
  _globals['_CALCULATEREQUEST']._serialized_end=506
  _globals['_CALCULATERESPONSE']._serialized_start=508
  _globals['_CALCULATERESPONSE']._serialized_end=579
  _globals['_NIFFLERCURRENCYSERVICE']._serialized_start=653
  _globals['_NIFFLERCURRENCYSERVICE']._serialized_end=859
# @@protoc_insertion_point(module_scope)