from .base_page_locators import BasePageLocators as BasePageLocators
from .login_page_locatorc import LoginPageLocators as LoginPageLocators
from .register_page_locators import RegisterPageLocators as RegisterPageLocators
