"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf.descriptor import (
    Descriptor,
    FileDescriptor,
)
from google.protobuf.message import (
    Message,
)
from typing import (
    final,
)

DESCRIPTOR: FileDescriptor


Empty: Empty

class Empty(Message):
    DESCRIPTOR: Descriptor

    def __init__(
        self,
    ) -> None: ...