"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from builtins import (
    bool,
    int,
)
from google.protobuf.descriptor import (
    Descriptor,
    FileDescriptor,
)
from google.protobuf.internal.well_known_types import (
    Timestamp,
)
from google.protobuf.message import (
    Message,
)
from typing import (
    Literal,
    final,
    overload,
)

DESCRIPTOR: FileDescriptor


Timestamp: Timestamp

class Timestamp(Message, Timestamp):
    DESCRIPTOR: Descriptor

    SECONDS_FIELD_NUMBER: int
    NANOS_FIELD_NUMBER: int
    seconds: int
    nanos: int
    def __init__(
        self,
        *,
        seconds: int | None = ...,
        nanos: int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: Literal["_nanos", b"_nanos", "_seconds", b"_seconds", "nanos", b"nanos", "seconds", b"seconds"]) -> bool: ...
    def ClearField(self, field_name: Literal["_nanos", b"_nanos", "_seconds", b"_seconds", "nanos", b"nanos", "seconds", b"seconds"]) -> None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_nanos", b"_nanos"]) -> Literal["nanos"] | None: ...
    @overload
    def WhichOneof(self, oneof_group: Literal["_seconds", b"_seconds"]) -> Literal["seconds"] | None: ...